'use client';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { FirebaseApp, initializeApp } from 'firebase/app';
import { createContext, useEffect } from 'react';
import { app } from './lib/firebaseConfig';
import Script from 'next/script';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>

      <Script src="https://www.google.com/recaptcha/enterprise.js?render=6LeTMVwrAAAAAA6QRkCDbDsoku23jaD5Xg6k4gwy"></Script>

    </html>
  );
}
