"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FirebaseApp, initializeApp } from "firebase/app";
import { createContext, useEffect } from "react";
import { app } from "./lib/firebaseConfig";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const FirebaseContext = createContext<FirebaseApp | null>(null);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const firebaseApp:FirebaseApp = app
  const FirebaseProvider = FirebaseContext.Provider;
  return (

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FirebaseProvider value={firebaseApp}>
            {children}
        </FirebaseProvider>
      </body>
    </html>
  );
}
